### PR TITLE
Updates to cfr

### PR DESCRIPTION
**Pull request by liach**
This includes some patches since e754b42b160a2f949cf12115865a5564d0ca2e4c which enables advanced functions, such as extending the output dumper for custom enigma output more easily, adding support for javadoc injection, etc.

Since I rebased the 2 commits onto the head of cfr, this pr cannot be merged; it can only be merged when the head of fabric cfr main branch is `git reset --hard` to the head of upstream cfr.

Poking @modmuss50 for a potential review later

### CODE REVIEW

**Comment by liach** [comment]
Just realized that we might need to tweak the buildscript once more due to how jenkins has been phased out in favor of github actions

**Comment by modmuss50** [comment]
No idea whats happened to this PR, ill merge upstream master into our fork, and hopefully you can sort it out.

**Comment by liach** [comment]
You can just rebase the current master onto upstream master. Then the pr should be mergeable

**Comment by modmuss50** [comment]
Doesnt seem to have sloved its self.

**Comment by liach** [comment]
Moving to #3

**Pull request closed without merging**
