### PR TITLE
Fix javadocs not showing on enums and annotation classes

### PR DESCRIPTION
**Pull request by YanisBft**
Tested and it worked

### CODE REVIEW

**Review by Player3324 — APPROVED** [review]
thanks!

**Review by modmuss50 — APPROVED** [review]

**Review by liach — APPROVED** [review]
Thanks, I never properly tested my patches on enums or annotations!

**Comment by liach** [comment]
@YanisBft mind add a patch from here? https://github.com/FabricMC/Enigma/issues/345#issuecomment-822511431

i.e. change https://github.com/FabricMC/cfr/pull/4/files#diff-75e114fefbcb1dc50272db78078d01e5c0da147137e2c487f16adc39ece092f0R37
from
https://github.com/FabricMC/cfr/blob/ab2cc7dabb9248d6e9eef3818f5b323421b32cfd/src/org/benf/cfr/reader/entities/classfilehelpers/ClassFileDumperEnum.java#L37
to 
```java
d.print("enum ").dump(c.getThisClassConstpoolEntry().getTypeInstance(), true).print(" ");
```

**Comment by liach** [comment]
Just curious, is merging upstream a concern? This should be compatible with upstream and should be safe to merge.

**Pull request merged**
